### ISSUE TITLE
Please note that also the folder scripts has to be renamed in src

### ISSUE THREAD

**Issue by JonathanGruner** [PilzDE/pilz_templates#17]
ROS Standard...
Maybe you have to change it in ROSwiki-Tutorials too.
Unfortunaly Idk how to change file names in Github (I just have the browser version)

**Comment by ct2034** [comment]
Hi Jonny, 
thanks. But could you please explaining what you want to do.

It is currently in line with what I see as common practice: A src folder would contain python modules to be installed. And user-executable scripts in the scripts folder.

**Comment by jschleicher** [comment]
> user-executable scripts in the scripts folder

For reference see
http://docs.ros.org/melodic/api/catkin/html/howto/format2/installing_python.html

**Comment by JonathanGruner** [comment]
Okay it seems like I don't know the naming convention, where is the official documentation on how to design a workspace?

**Comment by jschleicher** [comment]
@JonathanGruner From the link above: 
> Standard ROS practice is to place all executable Python programs in a package subdirectory named nodes/ or scripts/

**Comment by JonathanGruner** [comment]
@jschleicher ok I have overlooked the comment above. It makes sense now, thank you all for the kind support!
