### ISSUE TITLE
Question robot semantic

### ISSUE THREAD

**Issue by JonathanGruner** [PilzDE/pilz_templates#3]
Whats the reason for commented out line 53 to 54?
Just delete it (my opinion) than it would be consistent. I just changed the path in line 52. i didn't even recocnized the commented out custom file parameter.

**Comment by jschleicher** [comment]
Thank You. I've dropped the default (uncommented) parameter, since move_group already loads that indirectly. If you want to override the SRDF, you can uncomment the line and have no duplication any more.
