### ISSUE TITLE
Should this be a templates repo?

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_templates#9]
![Screenshot from 2019-07-30 10-35-58](https://user-images.githubusercontent.com/6976069/62113970-f02fcd00-b2b5-11e9-8d57-63d92e3d5b1b.png)

**Comment by ct2034** [comment]
https://github.com/PilzDE/pilz_templates/settings

**Comment by jschleicher** [comment]
Yep. Absolutely. Thanks for the hint.
